# Generated by Django 4.2.6 on 2023-11-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0003_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="background_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/background/"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/profile/"),
        ),
    ]
