# Generated by Django 4.2.6 on 2023-11-08 01:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("social", "0004_profile_background_image_profile_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="twitter_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
