# Generated by Django 4.2.6 on 2023-11-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0005_message_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_bio",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_location",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_website",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
