# Generated by Django 4.2.6 on 2023-11-28 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0006_profile_profile_bio_profile_profile_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="parent_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="social.message",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_bio",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
